#jwt
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=86400000

#kakao-login
spring.kakao.auth.client=${KAKAO_CLIENT_ID}
spring.kakao.auth.redirect=${KAKAO_REDIRECT_URI}

#kakao-pay
kakaopay.secretKey=${KAKAOPAY_SECRET_KEY}
kakaopay.cid=${KAKAOPAY_CID}

#mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Spring JPA
spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

#S3
cloud.aws.credentials.accessKey=${S3_ACCESS}
cloud.aws.credentials.secretKey=${S3_SECRET}
cloud.aws.s3.bucket=${BUCKET_NAME}
cloud.aws.region.static=${REGION}
cloud.aws.stack.auto-=false

server.address=0.0.0.0
server.port=8080

app.base-url=http://${EC2_PUBLIC_IP}:8080
