name: Deploy Ebooki to EC2

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/ebooki

          docker-compose stop app || true
          docker-compose rm -f app || true
        
          docker-compose build app
          docker-compose up -d app
        
          docker-compose ps
